# Generated by Django 6.0.6 on 2026-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
