# Generated by manual addition

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_courier_name_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ledger_credited',
            field=models.BooleanField(default=False),
        ),
    ]
