# Generated by Django 6.0.6 on 2026-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_ledger_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('sslcommerz', 'SSLCommerz'), ('cod', 'Cash on Delivery')], max_length=20, null=True),
        ),
    ]
