# Generated by Django 6.0.6 on 2026-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('sslcommerz', 'SSLCommerz'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
