# Generated by Django 6.0.6 on 2026-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
