# Generated by Django 6.0.6 on 2026-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sellerprofile_subdomain_sellerprofile_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='stripe_connected',
            field=models.BooleanField(default=False),
        ),
    ]
