# Generated by Django 6.0.6 on 2026-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
