# Generated by manual addition

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_sellerprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='balance',
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0.00),
        ),
    ]
